services:
  database:
    image: postgres:17-alpine
    container_name: vion_tracker_db
    restart: unless-stopped
    networks:
      - backend-network
    environment:
      POSTGRES_USER: ${DB_USER:-vion}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vion}
      POSTGRES_DB: ${DB_NAME:-vion_tracker}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: vion_tracker_redis
    restart: unless-stopped
    networks:
      - backend-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  # Мережа для внутрішньої комунікації API та БД
  backend-network:
    driver: bridge
  # Мережа для зв'язку Фронтенда з API
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
